export { default as Navbar } from './Navbar/Navbar'
export { default as Footer } from './Footer/Footer'
export { default as Message } from './Messages/Message'
export { default as DeviceData } from './OS/DeviceData'
export { default as CustomData } from './OS/CustomData'