export { default as Home } from './Home/Home'
export { default as Dashboard } from './Dashboard/Dashboard'
export { default as ServiceOrder } from './ServiceOrder/ServiceOrder'
export { default as Login } from './Auth/Login'
export { default as Register } from './Auth/Register'
export { default as OrderDetails } from './OrderDetails/OrderDetails'
export { default as Settings } from './Settings/Settings'
export { default as Tutorial } from './Tutorial/Tutorial'